
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels: 
    name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
        name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - name: httpd:2.4-alpine